{
 "title": "Modem Stats Copy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current Upstream Rate",
   "type": "stat",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "upstream_current_rate" }
   ]
  },
  {
   "title": "Current Downstream Rate",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "downstream_current_rate" }
   ]
  },
  {
   "title": "Upstream Max Rate",
   "type": "graph",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    { "expr": "upstream_max_rate" }
   ]
  },
  {
   "title": "Downstream Max Rate",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    { "expr": "downstream_max_rate" }
   ]
  },
  {
   "title": "Upstream CRC Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "upstream_crc_errors" }
   ]
  },
  {
   "title": "Downstream CRC Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 9, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "downstream_crc_errors" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } }
 ]
}